// PrototypeSpec.tsx — Ported from Level 1 PrototypeSpec.jsx
'use client';
import { useState, useEffect, useRef } from "react";
import { THEMES, getTheme } from "@/lib/theme";

const STORAGE_KEY = "dk-stage3-protospec";
const FIDELITY = [
  { key: "paper", label: "Paper / Sketch", color: "#95A5A6" },
  { key: "low", label: "Lo-Fi Wireframe", color: "#3498DB" },
  { key: "mid", label: "Mid-Fi Interactive", color: "#E67E22" },
  { key: "high", label: "Hi-Fi Prototype", color: "#2ECC71" },
  { key: "code", label: "Code Prototype", color: "#8E44AD" },
];
const TOOLS = ["Figma", "v0", "Lovable", "Bolt", "Cursor", "Framer", "Sketch", "Paper", "Other"];

function useAutoSave(s) { const t = useRef(null); useEffect(() => { clearTimeout(t.current); t.current = setTimeout(() => { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(s)); } catch (e) {} }, 500); return () => clearTimeout(t.current); }, [s]); }
function loadSaved() { try { const r = localStorage.getItem(STORAGE_KEY); if (r) return JSON.parse(r); } catch (e) {} return null; }

export default function PrototypeSpec() {
  const [theme] = useState(getTheme); const t = THEMES[theme];
  const [mobile, setMobile] = useState(typeof window !== "undefined" ? window.innerWidth < 700 : false);
  useEffect(() => { const c = () => setMobile(window.innerWidth < 700); window.addEventListener("resize", c); return () => window.removeEventListener("resize", c); }, []);
  const [state, setState] = useState(() => loadSaved() || { name: "", fidelity: "mid", tool: "", screens: "", questionsToAnswer: "", scope: "", outOfScope: "", exportNotes: "" });
  const [toast, setToast] = useState(null);
  useAutoSave(state);
  useEffect(() => { if (toast) { const tm = setTimeout(() => setToast(null), 2500); return () => clearTimeout(tm); } }, [toast]);

  const update = (k, v) => setState(prev => ({ ...prev, [k]: v }));
  const fieldStyle = { width: "100%", padding: "8px 10px", background: t.input, border: `1px solid ${t.cardBorder}`, borderRadius: 8, fontSize: 12, color: t.text, outline: "none", boxSizing: "border-box", fontFamily: "'DM Sans',sans-serif", resize: "vertical" };
  const selectedFid = FIDELITY.find(f => f.key === state.fidelity) || FIDELITY[2];

  const generateMarkdown = () => {
    let md = `# Prototype Spec: ${state.name || "Untitled"}\n\n`;
    md += `## Fidelity: ${selectedFid.label}\n`;
    md += `## Tool: ${state.tool || "TBD"}\n\n`;
    md += `## Screens / Components\n${state.screens || "TBD"}\n\n`;
    md += `## Questions This Prototype Must Answer\n${state.questionsToAnswer || "TBD"}\n\n`;
    md += `## In Scope\n${state.scope || "TBD"}\n\n`;
    md += `## Out of Scope\n${state.outOfScope || "TBD"}\n\n`;
    if (state.exportNotes) md += `## Notes for Builder\n${state.exportNotes}\n`;
    md += `\n---\n*Generated by Arthur · Mission Control System*\n`;
    return md;
  };

  const exportMarkdown = () => { navigator.clipboard.writeText(generateMarkdown()); setToast("Markdown copied — paste into v0, Cursor, or Figma"); };
  const exportJSON = () => { navigator.clipboard.writeText(JSON.stringify({ stage: 3, framework: "prototype_spec", data: state, exported_at: new Date().toISOString() }, null, 2)); setToast("JSON copied"); };

  return (
    <div style={{ maxWidth: 900, margin: "0 auto", padding: mobile ? "20px 16px" : "32px 24px", fontFamily: "'DM Sans',sans-serif" }}>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=DM+Mono:wght@400;500&family=Playfair+Display:wght@700;800&display=swap" rel="stylesheet" />
      <div style={{ marginBottom: 28, borderBottom: "3px solid #2ECC71", paddingBottom: 16 }}>
        <p style={{ fontSize: 11, fontFamily: "'DM Mono',monospace", color: "#2ECC71", fontWeight: 600, letterSpacing: "0.15em", textTransform: "uppercase", marginBottom: 4 }}>Stage 3 · Design & MVP</p>
        <h1 style={{ fontSize: mobile ? 24 : 30, fontFamily: "'Playfair Display',serif", fontWeight: 800, color: t.text, margin: "0 0 6px" }}>Prototype Spec</h1>
        <p style={{ fontSize: 14, color: t.textMuted, margin: 0 }}>Define what to build, at what fidelity, and what questions it must answer. Export to v0/Cursor.</p>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
        <div>
          <p style={{ fontSize: 10, fontFamily: "'DM Mono',monospace", color: "#2ECC71", margin: "0 0 4px", fontWeight: 600 }}>PROTOTYPE NAME</p>
          <input value={state.name} onChange={e => update("name", e.target.value)} placeholder="e.g., RideX Booking Flow v1, Onboarding Prototype..." style={fieldStyle} />
        </div>

        <div>
          <p style={{ fontSize: 10, fontFamily: "'DM Mono',monospace", color: "#2ECC71", margin: "0 0 4px", fontWeight: 600 }}>FIDELITY LEVEL</p>
          <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
            {FIDELITY.map(f => (
              <button key={f.key} onClick={() => update("fidelity", f.key)} style={{ padding: "8px 14px", borderRadius: 8, fontSize: 12, fontWeight: 600, cursor: "pointer", border: `1px solid ${f.color}30`, background: state.fidelity === f.key ? `${f.color}20` : "transparent", color: state.fidelity === f.key ? f.color : t.textDim, flex: mobile ? "1 1 40%" : "none" }}>{f.label}</button>
            ))}
          </div>
        </div>

        <div>
          <p style={{ fontSize: 10, fontFamily: "'DM Mono',monospace", color: "#2ECC71", margin: "0 0 4px", fontWeight: 600 }}>TOOL</p>
          <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
            {TOOLS.map(tool => (
              <button key={tool} onClick={() => update("tool", tool)} style={{ padding: "6px 12px", borderRadius: 6, fontSize: 11, fontWeight: 600, cursor: "pointer", border: `1px solid ${t.cardBorder}`, background: state.tool === tool ? "#2ECC7120" : "transparent", color: state.tool === tool ? "#2ECC71" : t.textMuted }}>{tool}</button>
            ))}
          </div>
        </div>

        <div>
          <p style={{ fontSize: 10, fontFamily: "'DM Mono',monospace", color: "#2ECC71", margin: "0 0 4px", fontWeight: 600 }}>SCREENS / COMPONENTS TO BUILD</p>
          <textarea value={state.screens} onChange={e => update("screens", e.target.value)} rows={4} placeholder={"1. Home screen — search + nearby drivers\n2. Booking confirmation — pickup time estimate\n3. Ride tracking — real-time map\n4. Payment + rating"} style={fieldStyle} />
        </div>

        <div>
          <p style={{ fontSize: 10, fontFamily: "'DM Mono',monospace", color: "#E67E22", margin: "0 0 4px", fontWeight: 600 }}>QUESTIONS THIS PROTOTYPE MUST ANSWER</p>
          <textarea value={state.questionsToAnswer} onChange={e => update("questionsToAnswer", e.target.value)} rows={3} placeholder={"1. Do users understand the pickup time estimate?\n2. Is the booking flow completable in under 30 seconds?\n3. Do users trust the AI matching confidence indicator?"} style={fieldStyle} />
        </div>

        <div style={{ display: "grid", gridTemplateColumns: mobile ? "1fr" : "1fr 1fr", gap: 10 }}>
          <div>
            <p style={{ fontSize: 10, fontFamily: "'DM Mono',monospace", color: "#1B9C85", margin: "0 0 4px", fontWeight: 600 }}>IN SCOPE</p>
            <textarea value={state.scope} onChange={e => update("scope", e.target.value)} rows={3} placeholder="Core booking flow, pickup time display, basic map..." style={fieldStyle} />
          </div>
          <div>
            <p style={{ fontSize: 10, fontFamily: "'DM Mono',monospace", color: "#E74C3C", margin: "0 0 4px", fontWeight: 600 }}>OUT OF SCOPE</p>
            <textarea value={state.outOfScope} onChange={e => update("outOfScope", e.target.value)} rows={3} placeholder="Payment integration, multi-stop, scheduling, accessibility..." style={fieldStyle} />
          </div>
        </div>

        <div>
          <p style={{ fontSize: 10, fontFamily: "'DM Mono',monospace", color: t.textDim, margin: "0 0 4px", fontWeight: 600 }}>NOTES FOR BUILDER (exported with Markdown)</p>
          <textarea value={state.exportNotes} onChange={e => update("exportNotes", e.target.value)} rows={2} placeholder="Technical notes, API requirements, design system reference..." style={fieldStyle} />
        </div>
      </div>

      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 18 }}>
        <button onClick={exportMarkdown} style={{ padding: "12px 20px", background: "#2ECC71", color: "#fff", border: "none", borderRadius: 10, fontSize: 14, fontWeight: 600, cursor: "pointer", flex: 1, minWidth: 140, minHeight: 48 }}>📋 Export Markdown (v0/Cursor)</button>
        <button onClick={exportJSON} style={{ padding: "12px 20px", background: t.text, color: t.bg, border: "none", borderRadius: 10, fontSize: 14, fontWeight: 600, cursor: "pointer", flex: 1, minWidth: 140, minHeight: 48 }}>📤 Export JSON</button>
      </div>
      <p style={{ fontSize: 11, color: t.textDim, fontFamily: "'DM Mono',monospace", textAlign: "center", marginTop: 16 }}>Auto-saved to localStorage</p>
      {toast && <div style={{ position: "fixed", bottom: 32, left: "50%", transform: "translateX(-50%)", padding: "12px 24px", background: "#1B9C85", color: "#fff", borderRadius: 10, fontSize: 13, fontWeight: 600, boxShadow: "0 4px 20px rgba(0,0,0,0.25)", zIndex: 1000 }}>{toast}</div>}
    </div>
  );
}
