// UserStories.tsx — Ported from Level 1 UserStories.jsx
'use client';
import { useState, useEffect, useRef } from "react";
import { THEMES, getTheme } from "@/lib/theme";
const STORAGE_KEY = "dk-stage4-stories";
const EMPTY = { asA: "", iWant: "", soThat: "", priority: "must", acceptanceCriteria: [""], notes: "" };
const PRIORITIES = [{ key:"must",label:"Must",color:"#E74C3C" },{ key:"should",label:"Should",color:"#E67E22" },{ key:"could",label:"Could",color:"#F1C40F" },{ key:"wont",label:"Won't",color:"#95A5A6" }];
function useAutoSave(s) { const t=useRef(null); useEffect(()=>{clearTimeout(t.current); t.current=setTimeout(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}catch(e){}},500); return()=>clearTimeout(t.current);}, [s]); }
function loadSaved() { try{const r=localStorage.getItem(STORAGE_KEY); if(r) return JSON.parse(r);}catch(e){} return null; }

export default function UserStories() {
  const [theme]=useState(getTheme); const t=THEMES[theme];
  const [mobile,setMobile]=useState(typeof window !== "undefined" ? window.innerWidth < 700 : false);
  useEffect(()=>{const c=()=>setMobile(window.innerWidth<700); window.addEventListener("resize",c); return()=>window.removeEventListener("resize",c);}, []);
  const [state,setState]=useState(()=>loadSaved()||{stories:[{...EMPTY,acceptanceCriteria:[""]}]});
  const [toast,setToast]=useState(null);
  useAutoSave(state);
  useEffect(()=>{if(toast){const tm=setTimeout(()=>setToast(null),2500); return()=>clearTimeout(tm);}}, [toast]);
  const update=(i,k,v)=>setState(prev=>{const s=[...prev.stories]; s[i]={...s[i],[k]:v}; return{...prev,stories:s};});
  const addStory=()=>setState(prev=>({...prev,stories:[...prev.stories,{...EMPTY,acceptanceCriteria:[""]}]}));
  const removeStory=(i)=>setState(prev=>({...prev,stories:prev.stories.filter((_,j)=>j!==i)}));
  const updateAC=(si,ai,v)=>setState(prev=>{const s=[...prev.stories]; const ac=[...s[si].acceptanceCriteria]; ac[ai]=v; s[si]={...s[si],acceptanceCriteria:ac}; return{...prev,stories:s};});
  const addAC=(si)=>setState(prev=>{const s=[...prev.stories]; s[si]={...s[si],acceptanceCriteria:[...s[si].acceptanceCriteria,""]}; return{...prev,stories:s};});
  const fieldStyle={width:"100%",padding:"8px 10px",background:t.input,border:`1px solid ${t.cardBorder}`,borderRadius:8,fontSize:12,color:t.text,outline:"none",boxSizing:"border-box",fontFamily:"'DM Sans',sans-serif",resize:"vertical"};
  const exportLinear=()=>{let md="# User Stories\n\n"; state.stories.forEach((s,i)=>{md+=`## US-${String(i+1).padStart(3,"0")} [${s.priority.toUpperCase()}]\n**As a** ${s.asA||"..."}\n**I want** ${s.iWant||"..."}\n**So that** ${s.soThat||"..."}\n\n`; if(s.acceptanceCriteria.filter(Boolean).length>0){md+="**Acceptance Criteria:**\n"; s.acceptanceCriteria.filter(Boolean).forEach(ac=>{md+=`- [ ] ${ac}\n`;}); } if(s.notes) md+=`\n*${s.notes}*\n`; md+="\n---\n\n";}); md+="*Generated by Arthur MCS*\n"; navigator.clipboard.writeText(md); setToast("Linear-format copied");};

  return (
    <div style={{maxWidth:900,margin:"0 auto",padding:mobile?"20px 16px":"32px 24px",fontFamily:"'DM Sans',sans-serif"}}>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=DM+Mono:wght@400;500&family=Playfair+Display:wght@700;800&display=swap" rel="stylesheet"/>
      <div style={{marginBottom:28,borderBottom:"3px solid #3498DB",paddingBottom:16}}>
        <p style={{fontSize:11,fontFamily:"'DM Mono',monospace",color:"#3498DB",fontWeight:600,letterSpacing:"0.15em",textTransform:"uppercase",marginBottom:4}}>Stage 4 · Planning & Roadmaps</p>
        <h1 style={{fontSize:mobile?24:30,fontFamily:"'Playfair Display',serif",fontWeight:800,color:t.text,margin:"0 0 6px"}}>User Stories & Acceptance Criteria</h1>
        <p style={{fontSize:14,color:t.textMuted,margin:0}}>As a [user], I want [action] so that [outcome]. Export to Linear.</p>
      </div>
      {state.stories.map((story,i)=>{const pr=PRIORITIES.find(p=>p.key===story.priority)||PRIORITIES[0]; return(
        <div key={i} style={{marginBottom:12,background:t.card,border:`1px solid ${pr.color}30`,borderRadius:14,borderLeft:`4px solid ${pr.color}`,overflow:"hidden"}}>
          <div style={{padding:"12px 14px",borderBottom:`1px solid ${t.cardBorder}`,display:"flex",alignItems:"center",gap:8}}>
            <span style={{fontSize:12,fontWeight:800,color:"#3498DB",fontFamily:"'DM Mono',monospace"}}>US-{String(i+1).padStart(3,"0")}</span>
            <div style={{display:"flex",gap:3,marginLeft:"auto"}}>{PRIORITIES.map(p=>(<button key={p.key} onClick={()=>update(i,"priority",p.key)} style={{padding:"3px 8px",borderRadius:5,fontSize:10,fontWeight:600,cursor:"pointer",border:`1px solid ${p.color}30`,background:story.priority===p.key?`${p.color}20`:"transparent",color:story.priority===p.key?p.color:t.textDim}}>{p.label}</button>))}</div>
            {state.stories.length>1&&<button onClick={()=>removeStory(i)} style={{background:"none",border:"none",color:"#E74C3C60",cursor:"pointer",fontSize:14}}>×</button>}
          </div>
          <div style={{padding:"12px 14px"}}>
            <div style={{display:"grid",gridTemplateColumns:mobile?"1fr":"1fr 1fr 1fr",gap:6,marginBottom:8}}>
              <div><p style={{fontSize:10,color:"#3498DB",margin:"0 0 3px",fontFamily:"'DM Mono',monospace",fontWeight:600}}>AS A</p><input value={story.asA} onChange={e=>update(i,"asA",e.target.value)} placeholder="user type..." style={fieldStyle}/></div>
              <div><p style={{fontSize:10,color:"#E67E22",margin:"0 0 3px",fontFamily:"'DM Mono',monospace",fontWeight:600}}>I WANT TO</p><input value={story.iWant} onChange={e=>update(i,"iWant",e.target.value)} placeholder="action..." style={fieldStyle}/></div>
              <div><p style={{fontSize:10,color:"#1B9C85",margin:"0 0 3px",fontFamily:"'DM Mono',monospace",fontWeight:600}}>SO THAT</p><input value={story.soThat} onChange={e=>update(i,"soThat",e.target.value)} placeholder="outcome..." style={fieldStyle}/></div>
            </div>
            <p style={{fontSize:10,color:t.textDim,margin:"0 0 4px",fontFamily:"'DM Mono',monospace"}}>ACCEPTANCE CRITERIA</p>
            {story.acceptanceCriteria.map((ac,ai)=>(<div key={ai} style={{display:"flex",alignItems:"center",gap:6,marginBottom:3}}><span style={{fontSize:10,color:t.textDim}}>☐</span><input value={ac} onChange={e=>updateAC(i,ai,e.target.value)} placeholder="Given... When... Then..." style={{...fieldStyle,flex:1,fontSize:11}}/></div>))}
            <button onClick={()=>addAC(i)} style={{fontSize:10,color:t.textMuted,background:"none",border:"none",cursor:"pointer",padding:"4px 0"}}>+ criteria</button>
            <textarea value={story.notes} onChange={e=>update(i,"notes",e.target.value)} rows={1} placeholder="Notes..." style={{...fieldStyle,marginTop:6,fontSize:11}}/>
          </div>
        </div>);})}
      <button onClick={addStory} style={{width:"100%",padding:"12px",background:"none",border:`1px dashed ${t.cardBorder}`,borderRadius:10,fontSize:13,color:t.textMuted,cursor:"pointer",marginBottom:18}}>+ Add User Story</button>
      <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>
        <button onClick={exportLinear} style={{padding:"12px 20px",background:"#3498DB",color:"#fff",border:"none",borderRadius:10,fontSize:14,fontWeight:600,cursor:"pointer",flex:1,minHeight:48}}>📋 Export Linear Format</button>
        <button onClick={()=>{navigator.clipboard.writeText(JSON.stringify({stage:4,framework:"stories",data:state,exported_at:new Date().toISOString()},null,2)); setToast("JSON copied");}} style={{padding:"12px 20px",background:t.text,color:t.bg,border:"none",borderRadius:10,fontSize:14,fontWeight:600,cursor:"pointer",flex:1,minHeight:48}}>📤 Export JSON</button>
      </div>
      <p style={{fontSize:11,color:t.textDim,fontFamily:"'DM Mono',monospace",textAlign:"center",marginTop:16}}>Auto-saved</p>
      {toast&&<div style={{position:"fixed",bottom:32,left:"50%",transform:"translateX(-50%)",padding:"12px 24px",background:"#1B9C85",color:"#fff",borderRadius:10,fontSize:13,fontWeight:600,boxShadow:"0 4px 20px rgba(0,0,0,0.25)",zIndex:1000}}>{toast}</div>}
    </div>);
}
